### ISSUE TITLE
Unable to use with  WordPress Android App

### ISSUE THREAD

**Issue by KowalskiOmniROM** [kevinvess/wp-force-login#4]
wp-force-login does not work with WordPress Android App (https://play.google.com/store/apps/details?id=org.wordpress.android)

---
WordPress Android version: 3.9
Android device name: Asus Nexus 7

01 - resetting suggestion table
02 - WPLaunchActivity,  activityName: LOGIN, activityId: Login Screen, intent: null
03 - Launch default Activity: PostsActivity
04 - WordPress.onCreate: begin
05 - WordPress.onCreate:      1311 ms, PostsActivity.onCreate
06 - WordPress.onCreate: end, 1311 ms
07 - No accounts configured.  Sending user to set up an account
08 - NewAccountAbstractOage.onCreate()
09 - trackLastActivity, activityId: Login Screen
10 - unresolved: &rsaquo; (position:TEXT @10:25 in java.io.StringReader@c79551b) 
11 - StackTrace: org.xmlpull.v1.XmlPullParserException: unresolved: &rsaquo; (position:TEXT @10:25 in java.io.StringReader@c79551b) 
	at org.kxml2.io.KXmlParser.checkRelaxed(KXmlParser.java:305)
	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1284)
	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1401)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at org.xmlrpc.android.ApiHelper.getRSDMetaTagHref(ApiHelper.java:1166)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getRsdUrl(FetchBlogListWPOrg.java:134)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getSelfHostedXmlrpcUrl(FetchBlogListWPOrg.java:254)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.fetchBlogList(FetchBlogListWPOrg.java:112)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListAbstract$1.run(FetchBlogListAbstract.java:27)

12 - Error while parsing the XML-RPC response document received from the server. - exception: unexpected type (position:END_DOCUMENT null@1:1 in java.io.InputStreamReader@3579a6b8) 
13 - StackTrace: org.xmlpull.v1.XmlPullParserException: unexpected type (position:END_DOCUMENT null@1:1 in java.io.InputStreamReader@3579a6b8) 
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2054)
	at org.xmlrpc.android.XMLRPCClient.parseXMLRPCResponse(XMLRPCClient.java:288)
	at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:493)
	at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:408)
	at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:225)
	at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:220)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getXmlrpcByUserEnteredPath(FetchBlogListWPOrg.java:157)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getSelfHostedXmlrpcUrl(FetchBlogListWPOrg.java:270)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.fetchBlogList(FetchBlogListWPOrg.java:112)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListAbstract$1.run(FetchBlogListAbstract.java:27)

14 - Response document received from the server: <!DOCTYPE html>
	
	
		<html xmlns="http://www.w3.org/1999/xhtml" lang="fr-FR">
	
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>***My_Blog_Title*** &rsaquo; Se connecter</title>
	<link rel='stylesheet' id='buttons-css'  href='http://***MY_URL***/wp-includes/css/buttons.min.css?ver=4.1.2' type='text/css' media='all' />
<link rel='stylesheet' id='open-sans-css'  href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.1.2' type='text/css' media='all' />
<link rel='stylesheet' id='dashicons-css'  href='http://***MY_URL***/wp-includes/css/dashicons.min.css?ver=4.1.2' type='text/css' media='all' />
<link rel='stylesheet' id='login-css'  href='http://***MY_URL***/wp-admin/css/login.min.css?ver=4.1.2' type='text/css' media='all' />
<s
15 - system.listMethods failed on: http://***MY_URL***
16 - Error while parsing the XML-RPC response document received from the server. - exception: unexpected type (position:END_DOCUMENT null@1:1 in java.io.InputStreamReader@3fe83c91) 
17 - StackTrace: org.xmlpull.v1.XmlPullParserException: unexpected type (position:END_DOCUMENT null@1:1 in java.io.InputStreamReader@3fe83c91) 
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2054)
	at org.xmlrpc.android.XMLRPCClient.parseXMLRPCResponse(XMLRPCClient.java:288)
	at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:493)
	at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:408)
	at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:225)
	at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:220)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getXmlrpcByUserEnteredPath(FetchBlogListWPOrg.java:204)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getSelfHostedXmlrpcUrl(FetchBlogListWPOrg.java:270)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.fetchBlogList(FetchBlogListWPOrg.java:112)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListAbstract$1.run(FetchBlogListAbstract.java:27)

18 - Response document received from the server: <!DOCTYPE html>
	
	
		<html xmlns="http://www.w3.org/1999/xhtml" lang="fr-FR">
	
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>***My_Blog_Title*** &rsaquo; Se connecter</title>
	<link rel='stylesheet' id='buttons-css'  href='http://***MY_URL***/wp-includes/css/buttons.min.css?ver=4.1.2' type='text/css' media='all' />
<link rel='stylesheet' id='open-sans-css'  href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.1.2' type='text/css' media='all' />
<link rel='stylesheet' id='dashicons-css'  href='http://***MY_URL***/wp-includes/css/dashicons.min.css?ver=4.1.2' type='text/css' media='all' />
<link rel='stylesheet' id='login-css'  href='http://***MY_URL***/wp-admin/css/login.min.css?ver=4.1.2' type='text/css' media='all' />
<s
19 - system.listMethods failed on: http://***MY_URL***/xmlrpc.php - exception: unexpected type (position:END_DOCUMENT null@1:1 in java.io.InputStreamReader@3fe83c91) 
20 - StackTrace: org.xmlpull.v1.XmlPullParserException: unexpected type (position:END_DOCUMENT null@1:1 in java.io.InputStreamReader@3fe83c91) 
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2054)
	at org.xmlrpc.android.XMLRPCClient.parseXMLRPCResponse(XMLRPCClient.java:288)
	at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:493)
	at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:408)
	at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:225)
	at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:220)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getXmlrpcByUserEnteredPath(FetchBlogListWPOrg.java:204)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getSelfHostedXmlrpcUrl(FetchBlogListWPOrg.java:270)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.fetchBlogList(FetchBlogListWPOrg.java:112)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListAbstract$1.run(FetchBlogListAbstract.java:27)

21 - Server response:

**Comment by kevinvess** [comment]
The plugin blocks access to all page URLs by default; I believe you need to allow public access to the XML-RPC page to allow the Android or iOS app to access your site.

Try adding the following code to your theme's functions.php file:

```php
/**
 * Filter Force Login to allow exceptions for specific URLs.
 *
 * @return array An array of URLs. Must be absolute.
 **/
function my_forcelogin_whitelist() {
  return array(
    site_url( '/xmlrpc.php' )
  );
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);
```

**Comment by KowalskiOmniROM** [comment]
I use now "jonradio Private Site" https://wordpress.org/plugins/jonradio-private-site/
Anyway, Thank you for you answer.
